### PR TITLE
Implement cancel job operation for CLI

### PR DESCRIPTION
**Pull request by amritghimire**
This introduces a cancel job operation for CLI that can be used to
cancel a job running in studio.

Command:
`datachain studio cancel <JOB_ID`

### CODE REVIEW

**Review by dreadatour — APPROVED** [review]
Looks good to me!

I am not sure `datachain studio cancel` is a good command name, it is too general and not verbose enough IMO. But I have no better options.

**Comment by amritghimire** [comment]
> thanks @amritghimire !
> 
> 
> 
> `datachain studio cancel <JOB_ID` 
> 
> 
> 
> let's rename it please though.
> 
> 
> 
> It should be:
> 
> 
> 
> `datachain job cancel --studio` (similar to `ds`)
> 

I think that it may be confusing to users since we don't have non studio version of job in local. The reason I included the cancel inside studio is that the operation is a concept totally located in Studio.

**Comment by amritghimire** [comment]
> same with `run`, same with API - it should be consistent + we should be using PUT, POST, DELETE, etc 
> 
> 
> 
> 

https://github.com/iterative/studio/pull/11077#discussion_r1885529578

**Comment by shcheklein** [comment]
> I think that it may be confusing to users since we don't have non studio version of job in local. The reason I included the cancel inside studio is that the operation is a concept totally located in Studio.

I see the point.

But, I don't think it justifies the inconsistency tbh (datasets, jobs, etc - all should be the same in API and in CLI to my mind). Also the name "datachain studio cancel" is strange a bit anymways. It should be then `datachain studio job cancel`

or let's find some other options please ...

**Comment by shcheklein** [comment]
> https://github.com/iterative/studio/pull/11077#discussion_r1885529578

is it PUT / POST though then?

**Comment by amritghimire** [comment]
> > I think that it may be confusing to users since we don't have non studio version of job in local. The reason I included the cancel inside studio is that the operation is a concept totally located in Studio.
> 
> I see the point.
> 
> But, I don't think it justifies the inconsistency tbh (datasets, jobs, etc - all should be the same in API and in CLI to my mind). Also the name "datachain studio cancel" is strange a bit anymways. It should be then `datachain studio job cancel`
> 
> or let's find some other options please ...

WDYT about `datachain studio cancel-job`?

>is it PUT / POST though then?

It is POST currently. We already have POST request for update-job.

**Comment by shcheklein** [comment]
> WDYT about datachain studio cancel-job?

I think it is still not good, since it's not consistent with datasets. We should be using the same general schema for all types of entities. This is quite important I think.

**Pull request merged**
