### PR TITLE
Remove legacy columns

### PR DESCRIPTION
**Pull request by rlamy**
This removes the following attributes or columns from various internal classes and tables: `vtype`, `dir_type`, `owner_name`, `owner_id`. Note that `Node.dir_type` is still used though.

The publicly visible, backwards-incompatible changes are:
* `File.vtype` is removed
* Existing listings table become invalid.

Part of #36

### CODE REVIEW

**Review by shcheklein — APPROVED** [review]
Looks good to me.

Do we need to invalidate listing on the Studio side or remove them? Does it also invalidate datasets (do they have these file fields inherited from listings)?

**Comment by rlamy** [comment]
@shcheklein This makes existing listing tables invalid, but I think that's irrelevant after #294. For datasets, the only change is that `File.vtype` is removed, but it wasn't used before so I don't think it'll cause any issue. Old dataset tables will just have an extra "file__vtype" column that should be ignored everywhere (UI, queries, ...).

**Comment by shcheklein** [comment]
@rlamy are we good to go here? :)

**Comment by rlamy** [comment]
@shcheklein The datachain part works, but we need the Studio tests to pass...

**Pull request merged**
