### PR TITLE
update examples tests timeout to be 30 minutes

### PR DESCRIPTION
**Pull request by mattseddon**
should be more than enough time

### CODE REVIEW

**Review by ilongin — APPROVED** [review]

**Review by dtulga — COMMENTED** [review]
It looks like one of the example test runs timed out at 25 minutes. Should the maximum runtime be increased (perhaps to a compromise value) or should those examples be sped up? I think this looks fine to me, as long as it doesn't introduce more flakiness.

**Comment by skshetry** [comment]
Do we need to run examples on all platforms and 2 python versions?

**Comment by mattseddon** [comment]
> Do we need to run examples on all platforms and 2 python versions?

I would say yes. If you're looking to save money see https://github.com/iterative/datachain/pull/276

**Review by dreadatour — APPROVED** [review]
Agree. Looks good to me 👀

**Comment by mattseddon** [comment]
less important now https://github.com/iterative/datachain/pull/276 has been merged

**Pull request closed without merging**
