### PR TITLE
use D replace "DataChain"

### PR DESCRIPTION
**Pull request by EdwardLi-coder**
Fix: from_parquet() return type #231

### CODE REVIEW

**Comment by dberenbaum** [comment]
Thanks @EdwardLi-coder! LGTM, but would you be willing to apply the same changes to the other `DataChain` methods?

**Comment by EdwardLi-coder** [comment]
> Thanks @EdwardLi-coder! LGTM, but would you be willing to apply the same changes to the other `DataChain` methods?

Sure,I will update.

**Comment by skshetry** [comment]
It's not clear what the issue is in #231, so I don't think we should replace a concrete type with a TypeVar. Returning `DataChain` or `Self` is the correct type here.

**Comment by dberenbaum** [comment]
@EdwardLi-coder Any objection to changing the return types to `Self`?

**Comment by EdwardLi-coder** [comment]
> @EdwardLi-coder Any objection to changing the return types to `Self`?

I have no objections to changing the return types to `Self`. If you think i need change the return types 'Datachain' to 'self'. I can adjust it.

**Comment by dmpetrov** [comment]
yeah, "Self" might look nicer in the code. Note, in some methods it's not needed.

**Comment by EdwardLi-coder** [comment]
> yeah, "Self" might look nicer in the code. Note, in some methods it's not needed.

I've only changed the return type of the method from "dataChain" to "self", and it doesn't have the @classmethod decorator. I'm not sure if this is appropriate, or if I should close this PR.

**Review by dberenbaum — APPROVED** [review]

**Comment by dberenbaum** [comment]
@skshetry @dmpetrov Do you want to review?

**Review by skshetry — APPROVED** [review]

**Comment by dberenbaum** [comment]
Thanks @EdwardLi-coder!

**Comment by dmpetrov** [comment]
Thank you @EdwardLi-coder! Congrats with your first commit to DataChain!

**Comment by EdwardLi-coder** [comment]
> Thank you @EdwardLi-coder! Congrats with your first commit to DataChain!

I'm really excited to make my first commit to DataChain. 🚀 This is an important milestone for me, I hope to make more contributions to DataChain in the future. Let's make DataChain even more awesome together! 💪😄​​​​​​​​​​​​​​​​

**Pull request merged**
