### PR TITLE
Llm bruteforce blog

### PR DESCRIPTION
**Pull request by volkfox**
adding a notebook for the blog

### CODE REVIEW

**Comment by shcheklein** [comment]
we should have already a repo for notebooks, I think @mnrozhkov and @tibor-mach created it. Let's move it there please.

**Review by dmpetrov — APPROVED** [review]
LG!

**Review by shcheklein — COMMENTED** [review]
The trick looks quite cool :) But what is the value of datachain here? (I guess I can wait for the blog post itself as well)

**Comment by shcheklein** [comment]
@volkfox I think we can close it here now?

**Pull request closed without merging**
