### PR TITLE
add_regexp_replace

### LINKED ISSUE #303: Need regexp_replace() function
### Description

It is common to transform text columns in datasets.

For example, if  class is encoded as part of the filename, one currently needs to write a mapper to extract label "cat" from the name "cat.1001.jpg" :

```
import re

def extract_label(filepath: str) -> str:
    match = re.search(r'\.(\pL+)\.', filepath)
    
    if match:
        return match.group(1)
    else:
        return None

map(label = lambda file:  extract_label(file.path))
```

It should be straightforward in many SQL engines to use regexp_replace() for this part:

```
mutate(label = regexp_replace(Column("file.path"), '\.(\pL+)\.', '\1') ))

```

### PR DESCRIPTION
**Pull request by EdwardLi-coder**
Adds `regexp_replace()` function. 

Closes #303

### CODE REVIEW

**Review by shcheklein — COMMENTED** [review]
Thanks @EdwardLi-coder ! It would be great to add a test for this.

**Comment by EdwardLi-coder** [comment]
> Thanks @EdwardLi-coder ! It would be great to add a test for this.

Thank you @shcheklein  for pointing that out. I apologize for forgetting to add a test. I will add one now.

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
Looks good, but we need also implement the ClickHouse part (that is used in the private Studio product). I'm getting atm:

```python
NotImplementedError: Compiler not implemented for the SQLAlchemy function, string.regexp_replace, with dialect, clickhouse. For information on adding dialect-specific compilers, see https://docs.sqlalchemy.org/en/14/core/compiler.html
```

let me try to help you here and create a companion PR is possible.

**Review by shcheklein — CHANGES_REQUESTED** [review]
Needs a companion PR on the Studio side. I'll try to look into this.

**Comment by shcheklein** [comment]
I've added a companion PR to the Studio (private) repo. Made small changes here (@EdwardLi-coder please review). It should be good to go @iterative/datachain

**Review by mattseddon — APPROVED** [review]

**Review by shcheklein — APPROVED** [review]

**Comment by EdwardLi-coder** [comment]
> I've added a companion PR to the Studio (private) repo. Made small changes here (@EdwardLi-coder please review). It should be good to go @iterative/datachain

Sorry. I only considered SQLite and wasn't aware that ClickHouse support also needed to be considered. In the future, when I try to solve similar problems, I will take it into account. I appreciate that you modified the code to make it more concise. Thank you.

**Pull request merged**
